services:
  db:
    image: postgres:15
    volumes:
      - postgres_crm_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=crm_db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "5433:5432"

  web:
    build: .
    command: >
      sh -c "while ! nc -z db 5432; do sleep 0.1; done;
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8001:8000"
    depends_on:
      - db
    links:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:postgres@db:5432/crm_db

volumes:
  postgres_crm_data:
